server:
  port: 8080

spring:
  application:
    name: hi-wms
  datasource:
    url: jdbc:postgresql://localhost:5432/hi_wms
    username: hi_wms
    password: change_me
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
